dist: xenial

language: python

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py36
    python: 3.6
  - env: TOX_ENV=py37
    python: 3.7
  - env: TOX_ENV=py38
    python: 3.8

install: pip install -r requirements/testing.txt

before_script:
  - sleep 1

script: tox -e $TOX_ENV

after_success:
  - pip install coveralls
  - coveralls
